version: '3.9'

services:
  federated-yolo-gpu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: federated-yolo-gpu
    privileged: true 
    devices:
      - /dev/dri
      - /dev/dri:/dev/dri
    group_add:
      - "video"
    volumes:
      - /dev/dri/by-path:/dev/dri/by-path
      - .:/app
      - /sys/class/powercap:/sys/class/powercap:ro
    working_dir: /app
    command: sh -c "python3 yolo.py --no-eval --batch_size 1 --device intel:gpu > results.txt 2>&1"
    environment:
      - PYTHONUNBUFFERED=1
      - YOLO_CONFIG_DIR=/tmp
    tty: true
